name: semantic-release-test
version: 0.0.0-semantically-released
summary: Test
description: Test

confinement: strict
base: core22
grade: stable

apps:
  semantic-release-test:
    command: semantic_release_test
    extensions: [gnome]

parts:
  semantic-release-test:
    plugin: dump
    source: build/linux/x64/release/bundle
